version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10-browsers

    working_directory: /tmp/webb
    steps:
      # install bazel
      - run:
          name: Install Bazel
          command: |
            sudo apt update && sudo apt upgrade -y
            sudo apt install apt-transport-https -y
            sudo apt install openjdk-11-jdk -y
            echo "deb [arch=amd64] https://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list
            curl https://bazel.build/bazel-release.pub.gpg | sudo apt-key add -
            sudo apt update -y && sudo apt install bazel -y

      # checkout the actual code
      - checkout

      # restore cached lfs
      - restore_cache:
          keys:
            - bazel-cached-anything

      # restore node_modules
      - restore_cache:
          keys:
            - dependencies-{{ checksum "yarn.lock" }}

      # install differences in node_modules
      - run: yarn install

      - save_cache:
          paths:
            - node_modules
          key: dependencies-{{ checksum "yarn.lock" }}

      - run:
          name: Run all bazel tests
          command: |
            bazel run cryptographic-identity:test -j 8 --local_ram_resources=8000

      - save_cache:
          paths:
            - /root/.cache/bazel
          key: bazel-cached-anything

workflows:
  version: 2
  build:
    jobs:
      - build
